---
apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application
version: v1.19.1
dependencies:
  - name: cert-manager
    version: v1.19.1
    repository: oci://quay.io/jetstack/charts
