argocd-apps:
  applications:
    applications:
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      destination:
        name: ''
        namespace: argocd
        server: 'https://kubernetes.default.svc'
      source:
        path: workloads/applications
        repoURL: 'https://github.com/schrenker/raspberry-nix.git'
        targetRevision: HEAD
      project: gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true

  projects:
    gitops:
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      description: Argocd and bunch
      sourceRepos:
        - 'https://github.com/schrenker/raspberry-nix.git'
      destinations:
        - namespace: argocd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    networking:
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      description: Networking
      sourceRepos:
        - 'https://github.com/schrenker/raspberry-nix.git'
      destinations:
        - namespace: cilium
          server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
