---
apiVersion: v2
name: k8s-monitoring
description: A Helm chart for Kubernetes
type: application
version: 3.5.6
dependencies:
  - name: k8s-monitoring
    version: 3.5.6
    repository: "https://grafana.github.io/helm-charts"
