apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-storage
  name: test-storage
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-storage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-storage
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        command:
          - sh
          - -c
          - sleep infinity
        volumeMounts:
          - name: test-claim
            mountPath: /mnt/pvc
      volumes:
        - name: test-claim
          persistentVolumeClaim:
            claimName: test-claim
status: {}
