---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: enforce-resource-definition
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments", "statefulsets", "daemonsets"]
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs", "cronjobs"]
  failurePolicy: Fail
  validations:
    - expression: |
        (kind in ["Deployment", "StatefulSet", "DaemonSet", "Job"] ? spec.template.spec.containers :
        (kind == "CronJob" ? spec.jobTemplate.spec.template.spec.containers : spec.containers)).all(container,
            has(container.resources) &&
            has(container.resources.requests) &&
            has(container.resources.requests.cpu) &&
            has(container.resources.requests.memory) &&
            has(container.resources.limits) &&
            has(container.resources.limits.memory) &&
            container.resources.requests.memory == container.resources.limits.memory)
      message: "All containers must specify CPU requests."
