---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: enforce-resource-definition
spec:
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["deployments", "statefulsets", "daemonsets"]
      - apiGroups: ["batch"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["jobs", "cronjobs"]
  failurePolicy: Fail
  validations:
    - expression: |
        (
          object.kind == 'Pod' ?
            (has(object.spec) && has(object.spec.containers) ? object.spec.containers : []) :
          (object.kind == 'Deployment' || object.kind == 'StatefulSet' || object.kind == 'DaemonSet' || object.kind == 'Job') ?
            (has(object.spec) && has(object.spec.template) && has(object.spec.template.spec) && has(object.spec.template.spec.containers) ? object.spec.template.spec.containers : []) :
          object.kind == 'CronJob' ?
            (has(object.spec) && has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec) && has(object.spec.jobTemplate.spec.template) && has(object.spec.jobTemplate.spec.template.spec) && has(object.spec.jobTemplate.spec.template.spec.containers) ? object.spec.jobTemplate.spec.template.spec.containers : []) :
          []
        ).all(container,
          has(container.resources) &&
          has(container.resources.requests) &&
          has(container.resources.requests.cpu)
        )
      message: "All containers must specify CPU requests."

    - expression: |
        (
          object.kind == 'Pod' ?
            (has(object.spec) && has(object.spec.containers) ? object.spec.containers : []) :
          (object.kind == 'Deployment' || object.kind == 'StatefulSet' || object.kind == 'DaemonSet' || object.kind == 'Job') ?
            (has(object.spec) && has(object.spec.template) && has(object.spec.template.spec) && has(object.spec.template.spec.containers) ? object.spec.template.spec.containers : []) :
          object.kind == 'CronJob' ?
            (has(object.spec) && has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec) && has(object.spec.jobTemplate.spec.template) && has(object.spec.jobTemplate.spec.template.spec) && has(object.spec.jobTemplate.spec.template.spec.containers) ? object.spec.jobTemplate.spec.template.spec.containers : []) :
          []
        ).all(container,
          has(container.resources) &&
          has(container.resources.requests) &&
          has(container.resources.requests.memory)
        )
      message: "All containers must specify memory requests."

    - expression: |
        (
          object.kind == 'Pod' ?
            (has(object.spec) && has(object.spec.containers) ? object.spec.containers : []) :
          (object.kind == 'Deployment' || object.kind == 'StatefulSet' || object.kind == 'DaemonSet' || object.kind == 'Job') ?
            (has(object.spec) && has(object.spec.template) && has(object.spec.template.spec) && has(object.spec.template.spec.containers) ? object.spec.template.spec.containers : []) :
          object.kind == 'CronJob' ?
            (has(object.spec) && has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec) && has(object.spec.jobTemplate.spec.template) && has(object.spec.jobTemplate.spec.template.spec) && has(object.spec.jobTemplate.spec.template.spec.containers) ? object.spec.jobTemplate.spec.template.spec.containers : []) :
          []
        ).all(container,
          has(container.resources) &&
          has(container.resources.limits) &&
          has(container.resources.limits.memory)
        )
      message: "All containers must specify memory limits."

    - expression: |
        (
          object.kind == 'Pod' ?
            (has(object.spec) && has(object.spec.containers) ? object.spec.containers : []) :
          (object.kind == 'Deployment' || object.kind == 'StatefulSet' || object.kind == 'DaemonSet' || object.kind == 'Job') ?
            (has(object.spec) && has(object.spec.template) && has(object.spec.template.spec) && has(object.spec.template.spec.containers) ? object.spec.template.spec.containers : []) :
          object.kind == 'CronJob' ?
            (has(object.spec) && has(object.spec.jobTemplate) && has(object.spec.jobTemplate.spec) && has(object.spec.jobTemplate.spec.template) && has(object.spec.jobTemplate.spec.template.spec) && has(object.spec.jobTemplate.spec.template.spec.containers) ? object.spec.jobTemplate.spec.template.spec.containers : []) :
          []
        ).all(container,
          quantity(container.resources.requests.memory) == quantity(container.resources.limits.memory)
        )
      message: "Memory requests must be equal to memory limits for all containers."
