bpf:
  vlanBypass:
  - 0
cluster:
  name: default
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
k8sServiceHost: 192.168.1.65
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
routingMode: tunnel
tunnelProtocol: vxlan
l2announcements:
  enabled: true
devices:
  - end0
