apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: cilium
    server: 'https://kubernetes.default.svc'
  source:
    path: workloads/cilium-config
    repoURL: 'https://github.com/schrenker/raspberry-nix.git'
    targetRevision: HEAD
  project: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
