---
k8s-monitoring:
  cluster:
    name: k3s

  destinations:
    - name: metrics
      type: otlp
      url: http://victoria-metrics-victoria-metrics-single-server:8428/opentelemetry/v1/metrics
      metrics:
        enabled: true
      logs:
        enabled: false

    - name: logs
      type: otlp
      url: http://victoria-logs-victoria-logs-single-server:9428/insert/opentelemetry/v1/logs
      metrics:
        enabled: false
      logs:
        enabled: true

  clusterMetrics:
    enabled: true
    opencost:
      enabled: false
  clusterEvents:
    enabled: true
  nodeLogs:
    enabled: true
  podLogs:
    enabled: true
  applicationObservability:
    enabled: false
  autoInstrumentation:
    enabled: false
  annotationAutodiscovery:
    enabled: false
  prometheusOperatorObjects:
    enabled: false
  profiling:
    enabled: false
  profilesReceiver:
    enabled: false
  alloy-metrics:
    enabled: true
  alloy-singleton:
    enabled: true
  alloy-logs:
    enabled: true
  alloy-receiver:
    enabled: false
  alloy-profiles:
    enabled: false
  alloy-operator:
    deploy: true
