kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - grafana.zawadzki.local

    grafana.ini:
      analytics:
        check_for_updates: false
        reporting_enabled: false
        check_for_plugins_updates: false

    persistence:
      enabled: true
      type: sts
      storageClassName: nfs-client
      accessModes:
        - ReadWriteOnce
      size: 20Gi
      finalizers:
        - kubernetes.io/pvc-protection

  kubeControllerManager:
    endpoints:
      - 192.168.1.65
    service:
      port: 10257
      targetPort: 10257
    serviceMonitor:
      https: true
      insecureSkipVerify: true
  kubeScheduler:
    endpoints:
      - 192.168.1.65
    service:
      port: 10259
      targetPort: 10259
    serviceMonitor:
      https: true
      insecureSkipVerify: true
  kubeEtcd:
    endpoints:
      - 192.168.1.65
    service:
      port: 2381
      targetPort: 2381

  kubeProxy:
    enabled: false

  prometheus-node-exporter:
    hostNetwork: false
    hostPID: false
    prometheus:
      monitor:
        relabelings:
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_ip
            targetLabel: pod_ip
          - action: replace
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: instance
