---
opentelemetry-collector:
  image:
    repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  mode: "daemonset"
  presets:
    logsCollection:
      enabled: true
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true

  config:
    # deltatocumulative processor is needed to convert metrics with delta temporality to cumulative temporality.
    # VictoriaMetrics doesn't support delta temporality. Skip this processor if you don't use delta temporality.
    # processors:
    #   deltatocumulative:
    #     max_stale: 5m
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        # metrics_endpoint: http://vmsingle-victoria-metrics-k8s-stack:8428/opentelemetry/v1/metrics
        logs_endpoint: http://victoria-logs-victoria-logs-single-server:9428/insert/opentelemetry/v1/logs
        tls:
          insecure: true
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/victoriametrics]
        # metrics:
        #   receivers: [otlp]
        #   # processors: [deltatocumulative]
        #   processors: []
        #   exporters: [otlphttp/victoriametrics]

  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists

  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      memory: 200Mi
