---

opentelemetry-collector:
  image:
    repository: "ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s"
  mode: "daemonset"
  presets:
    logsCollection:
      enabled: true
    kubernetesAttributes:
      enabled: true
      extractAllPodLabels: true
    kubeletMetrics:
      enabled: true
    clusterMetrics:
      enabled: true

  config:
    # deltatocumulative processor is needed to convert metrics with delta temporality to cumulative temporality.
    # VictoriaMetrics doesn't support delta temporality. Skip this processor if you don't use delta temporality.
    # processors:
    #   deltatocumulative:
    #     max_stale: 5m
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      otlphttp/victoriametrics:
        compression: gzip
        encoding: proto
        metrics_endpoint: http://victoria-metrics-victoria-metrics-single-server:8428/opentelemetry/v1/metrics
        logs_endpoint: http://victoria-logs-victoria-logs-single-server:9428/insert/opentelemetry/v1/logs
        tls:
          insecure: true
    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [otlphttp/victoriametrics]
        metrics:
          receivers: [otlp]
          processors: [deltatocumulative]
          exporters: [otlphttp/victoriametrics]

  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists

  extraEnvs: []
  extraEnvsFrom: []
  # This also supports template content, which will eventually be converted to yaml.
  # extraVolumes:
  #   - name: varlogpods
  #     hostPath:
  #       path: /var/log/pods
  #   - name: varlogcontainers
  #     hostPath:
  #       path: /var/log/containers

  # # This also supports template content, which will eventually be converted to yaml.
  # extraVolumeMounts:
  #   - name: varlogpods
  #     mountPath: /var/log/pods
  #     readOnly: true
  #   - name: varlogcontainers
  #     mountPath: /var/log/containers
  #     readOnly: true

  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      memory: 200Mi
