apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare
    namespace: cert-manager
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:woEmQg9k/86mj1soDloNvUNR0Ng=,iv:7U+GwRw2R4uDDWHWqEE601prRpc7AOZirpFdLYGcQVQ=,tag:kq+R78SiWbFrvJQ0kVDI2g==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:qrVHkIoQeM9ejqQGDXhbtoPc+R19MjN/GZfVdSoRGEfhRV3vc7g9NA==,iv:yGk8aNqrKST9ylvn5woWKLmhIdxGFXLikG7UYBMVdyE=,tag:qebmE+Tqm95nL9G2wfGwJg==,type:str]
            cf-email: ENC[AES256_GCM,data:eglo9OZbEzc5A2NPnilCMASt2eU+64PEJO44Juwg,iv:PusksP4JIla/2viqBq1cJfNTLEPM/CPdXDuSRv5MkP0=,tag:c/lfdNciv0jXkyiE1nS3Lw==,type:str]
sops:
    age:
        - recipient: age1ag62ygw4a29q0yjkzh4ufznfjnn29q7g8tw8zau3fz6092rd4etqgdpmzz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RVNsWThYK2R5WW1adlcz
            VW9PdVhSbkZSSnFQSjJPdW8zZXpmOFUyVmtvCnpmTkxZUUN3OEcrVCsyTzdkNFZs
            MkVqbHhxb29mc29uN0kvVXhRM09Cb0kKLS0tIGpqZGY0VzdxSHJ6VWlvdlk4bldw
            OHFMYy9CRUhSQkpjcUdub21YS3dSWmMKNo04a41A+vUtqOW45Zld6O5xPhwYr3TB
            d7hIE1ES2Kne9inOPupfP2GFdKVtEnNkENmoqu5RQTMPacXpqRFpgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-13T15:03:11Z"
    mac: ENC[AES256_GCM,data:EEg1m/DHCPErj6BsMF+slm2ttbnOmS0V5iIfCFj4/i2VFm5L/gMvolTwhpV1NbZwGFXwxkedwuhB2NGzR0RzMVMlr+0Nqpay/ruDHsUmddyf3JHA3NF4NqweiZiiUbzzEmcPS4usAAeroxr/2BrKKCoY/8GXgNkdwnlgbvx/Ql8=,iv:D+ZbGOGn8HQsTkEQCG13QM1BSmI0yzy6ahlPGG0KDAM=,tag:YtpFMhDwzz24c8JAEkaGFA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
