---
apiVersion: v2
name: loki
description: A Helm chart for Kubernetes
type: application
version: 6.46.0
dependencies:
  - name: loki
    version: 6.46.0
    repository: "https://grafana.github.io/helm-charts"
